/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  USER
 * Created: 02 3, 22
 */

update enrollment_student_loaded_subjects set status=1,is_payed=1 where enrollment_no='00006538' and status=0;

INSERT INTO `students` (`id`, `is_transferee`, `academic_year_id`, `academic_year`, `student_no`, `last_name`, `first_name`, `middle_name`, `nick_name`, `current_address`, `permanent_address`, `email_address`, `postal_code`, `tel_no`, `mobile_no`, `date_of_birth`, `place_of_birth`, `age`, `gender`, `citizenship`, `religion`, `civil_status`, `spouse_name`, `date_of_communion`, `date_of_confirmation`, `is_right_handed`, `is_indigenous`, `indigenous_name`, `level_id`, `level`, `college_id`, `college`, `department_id`, `department`, `year_level`, `year_level_status`, `preferred_course1`, `preferred_course2`, `preferred_course3`, `father_name`, `father_citizenship`, `father_home_address`, `father_email_address`, `father_mobile_no`, `father_occupation`, `father_employer`, `father_business_address`, `father_business_tel_no`, `father_educational_attainment`, `father_last_school_attended`, `mother_name`, `mother_citizenship`, `mother_home_address`, `mother_email_address`, `mother_mobile_no`, `mother_occupation`, `mother_employer`, `mother_business_address`, `mother_business_tel_no`, `mother_educational_attainment`, `mother_last_school_attended`, `guardian_name`, `guardian_mailing_address`, `guardian_telephone_no`, `grade_school_name`, `grade_school_region`, `grade_school_school_year`, `grade_school_awards`, `high_school_name`, `high_school_region`, `high_school_school_year`, `high_school_awards`, `college_school_name`, `college_school_region`, `college_school_school_year`, `college_awards`, `junior_high_name`, `junior_high_region`, `junior_high_year`, `junior_high_awards`, `tesda_name`, `tesda_region`, `tesda_year`, `tesda_awards`, `sibling1`, `sibling2`, `sibling3`, `sibling4`, `sibling5`, `sibling6`, `sibling7`, `sibling8`, `created_at`, `updated_at`, `created_by`, `updated_by`, `status`, `is_uploaded`, `course_id`, `course_code`, `course_description`, `date_enrolled`, `balance`, `prepaid`) VALUES
(508, 0, 9, '2020 - 2021', '20200506', 'MARIMON', 'ROSALIE', 'ATAYDE', 'IN-IN', 'NAPACAO, SIATON, NEGROS ORIENTAL', 'NAPACAO, SIATON, NEGROS ORIENTAL', 'inmarimon.3@gmail.com', '', '', '09067713975', '2001-12-25', 'SIATON, NEGROS ORIENTAL', 18, 0, 'Filipino', 'Roman Catholic', '1', '', NULL, NULL, 1, 0, '', 13, 'College of Allied Health and Sciences', 13, 'College of Allied Health and Sciences', 5, 'TERTIARY DEPARTMENT', 'First Year', NULL, '', '', '', 'RESTITUTO A. MARIMON SR.', 'FILIPINO', 'MAPACAO, SIATON, NEGROS ORIENTAL', '', '09974755294', '', '', '', '', '', '', 'MAJA A. MARIMON', 'FILIPINO', '', '', '', '', '', '', '', '', '', 'RESTITUTO A. MARIMON SR.', 'MAPACAO, SIATON, NEGROS ORIENTAL', '09974755294', 'LINDY PAJUNAR MEMORIAL SCHOOL', 'Region 7', '', '', '', 'Region 7', '', '', '', 'Region 7', '', '', 'JOSE MARIE LOCSIN MEMORIAL HIGH SCHOOL', 'Region 7', '', '', '', 'Region 7', '', '', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '2020-08-10 10:37:11', '2020-08-10 10:37:11', '12', '12', 0, 0, 216, 'MID 2018', 'Laderized BS in Midwifery Program', '2020-08-10', 12315, 0);

INSERT INTO `students` (`id`, `is_transferee`, `academic_year_id`, `academic_year`, `student_no`, `last_name`, `first_name`, `middle_name`, `nick_name`, `current_address`, `permanent_address`, `email_address`, `postal_code`, `tel_no`, `mobile_no`, `date_of_birth`, `place_of_birth`, `age`, `gender`, `citizenship`, `religion`, `civil_status`, `spouse_name`, `date_of_communion`, `date_of_confirmation`, `is_right_handed`, `is_indigenous`, `indigenous_name`, `level_id`, `level`, `college_id`, `college`, `department_id`, `department`, `year_level`, `year_level_status`, `preferred_course1`, `preferred_course2`, `preferred_course3`, `father_name`, `father_citizenship`, `father_home_address`, `father_email_address`, `father_mobile_no`, `father_occupation`, `father_employer`, `father_business_address`, `father_business_tel_no`, `father_educational_attainment`, `father_last_school_attended`, `mother_name`, `mother_citizenship`, `mother_home_address`, `mother_email_address`, `mother_mobile_no`, `mother_occupation`, `mother_employer`, `mother_business_address`, `mother_business_tel_no`, `mother_educational_attainment`, `mother_last_school_attended`, `guardian_name`, `guardian_mailing_address`, `guardian_telephone_no`, `grade_school_name`, `grade_school_region`, `grade_school_school_year`, `grade_school_awards`, `high_school_name`, `high_school_region`, `high_school_school_year`, `high_school_awards`, `college_school_name`, `college_school_region`, `college_school_school_year`, `college_awards`, `junior_high_name`, `junior_high_region`, `junior_high_year`, `junior_high_awards`, `tesda_name`, `tesda_region`, `tesda_year`, `tesda_awards`, `sibling1`, `sibling2`, `sibling3`, `sibling4`, `sibling5`, `sibling6`, `sibling7`, `sibling8`, `created_at`, `updated_at`, `created_by`, `updated_by`, `status`, `is_uploaded`, `course_id`, `course_code`, `course_description`, `date_enrolled`, `balance`, `prepaid`) VALUES
(859, 0, 9, '2020 - 2021', '20200857', 'QUITAY', 'MICAH', 'KILNET ', 'MICAH', 'NAGBA, MALOH, SIATON, NEGROS ORIENTAL', 'NAGBA, MALOH, SIATON, NEGROS ORIENTAL', 'micahquitayluvs0810@gmail.com', '', '', '09068336827', '1999-11-13', 'MALOH, SIATON, NEGROS ORIENTAL', 20, 0, 'Filipino', 'Roman Catholic', '1', '', NULL, NULL, 1, 0, '', 15, 'College of Criminal Justice Education', 15, 'College of Criminal Justice Education', 5, 'TERTIARY DEPARTMENT', 'Third Year', NULL, '', '', '', 'NESTOR G. QUITAY', 'FILIPINO', 'NAGBA, MALOH, SIATON, NEGROS ORIENTAL', '', '', 'FISHERMEN', '', '', '', '', '', 'ANA GLORIA M. KILNET', 'FILIPINO', 'NAGBA, MALOH, SIATON, NEGROS ORIENTAL', '', '09361277651', 'HOUSEWIFE', '', '', '', '', '', 'ANA GLORIA M. KILNET', 'NAGBA, MALOH, SIATON, NEGROS ORIENTAL', '09361277651', '', 'Region 7', '', '', '', 'Region 7', '', '', '', 'Region 7', '', '', '', 'Region 7', '', '', '', 'Region 7', '', '', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '%%%%%%', '2020-08-17 17:17:19', '2020-08-17 17:17:19', '12', '12', 0, 0, 192, 'BSCrim 2018', 'Bachelor of Science in Criminology', '2020-08-17', 12930, 0);

INSERT INTO `enrollment_student_loaded_subjects` (`enrollment_id`, `enrollment_no`, `student_id`, `student_no`, `fname`, `mi`, `lname`, `enrollment_offered_subject_section_id`, `enrollment_offered_subject_id`, `academic_offering_subject_id`, `academic_offering_id`, `academic_year_id`, `academic_year`, `level_id`, `level`, `college_id`, `college`, `department_id`, `department`, `course_id`, `course_code`, `course_description`, `term`, `year_level`, `subject_id`, `subject_code`, `description`, `lecture_units`, `lab_units`, `faculty_id`, `faculty_name`, `section`, `room_id`, `room`, `schedule`, `day`, `time`, `start_time`, `closing_time`, `created_at`, `updated_at`, `created_by`, `updated_by`, `status`, `is_uploaded`, `is_added`, `final_grade`, `final_grade_remarks`, `final_grade_created_at`, `final_grade_created_by`, `is_payed`, `retake`) VALUES
(3638, '00003574', 567, '20200565', 'ANDREA MAY ', 'DELA CERNA', 'MARGASIÑO', 1529, 810, 6829, 129, 10, '2021 - 2021', 0, '', 0, '', 5, 'TERTIARY DEPARTMENT', 192, 'BSCrim 2018', 'Bachelor of Science in Criminology', 'First Semester', 'Second Year', 1429, 'MS31', 'Advance ROTC', 3, 0, NULL, 'ROTC Instructor', 'A', 0, 'GYM', '', '&nbsp;&nbsp;Saturday: 02:00 PM-05:00 PM', '', NULL, NULL, '2022-02-11 11:06:41', '2022-02-11 11:06:41', '1', '1', 1, 0, 1, 0, NULL, NULL, NULL, 0, NULL);

delete from enrollment_student_loaded_subjects where id = 58790;

